version = 0.1

[default.deploy.parameters]
stack_name = "ecommerce-prod"
resolve_s3 = true
s3_prefix = "ecommerce-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
