AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: dotnet8
    MemorySize: 256
    Timeout: 10

Resources:
  ExamplesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Example
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-profile
      Runtime: python3.13
      Handler: get_profile.lambda_handler
      CodeUri: src/python/get_profile/
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: ecommerce
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ecommerce
      Events:
        GetProfileApi:
          Type: Api
          Properties:
            Path: /api/v1/profile
            Method: get 


  CreateExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create-example
      Runtime: dotnet8
      Handler: ExampleManager.Create::ExampleManager.Create.Function::FunctionHandler
      CodeUri: src/ExampleManager.Create/
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: Examples
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Examples
      Events:
        CreateExampleApi:
          Type: Api
          Properties:
            Path: /api/v1/examples
            Method: post
        
  GetExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-example
      Runtime: dotnet8
      Handler: ExampleManager.Get::ExampleManager.Get.Function::FunctionHandler
      CodeUri: src/ExampleManager.Get/
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: Examples
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Examples
      Events:
        CreateExampleApi:
          Type: Api
          Properties:
            Path: /api/v1/examples
            Method: get
