.PHONY: build build-GetOrdersFunction clean

build:
	go build -o bootstrap main.go
	cp bootstrap $(ARTIFACTS_DIR)/bootstrap

build-GetOrdersFunction:
	go build -o bootstrap main.go
	cp bootstrap $(ARTIFACTS_DIR)/bootstrap

clean:
	rm -f bootstrap